version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.8.0
    volumes:
      - /opt/loki/config/loki-config.yml:/etc/loki/loki-config.yml
      - /volumes/loki:/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.8.0
    volumes:
      - /opt/loki/config/promtail-config.yml:/etc/promtail/promtail-config.yml
      - /var/log/auth.log:/var/log/auth.log
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    volumes:
      - /opt/loki/config/grafana-defaults.ini:/usr/share/grafana/conf/defaults.ini
      - /volumes/grafana:/var/lib/grafana    
    ports:
      - "3000:3000"
    networks:
      - loki


  nginx:
    image: quay.io/dtan4/nginx-basic-auth-proxy
    environment:
      - BASIC_AUTH_USERNAME=loki_user
      - BASIC_AUTH_PASSWORD=loki_password
      - PROXY_PASS=http://loki:3100
      - PORT=3200
      - SERVER_NAME=_
    ports:
      - 3200:3200
      - 8090:8090
    networks:
      - loki

      
