version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.8.0
    volumes:
      - /opt/loki/config/loki-config.yml:/etc/loki/loki-config.yml
      - /volumes/loki:/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.8.0
    volumes:
      - /opt/loki/config/promtail-config.yml:/etc/promtail/promtail-config.yml
      - /var/log/auth.log:/var/log/auth.log
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    volumes:
      - /opt/loki/config/grafana-defaults.ini:/usr/share/grafana/conf/defaults.ini
      - /volumes/grafana:/var/lib/grafana    
    ports:
      - "3000:3000"
    networks:
      - loki
